### ISSUE TITLE
Vanilla server 1.21.3 kick

### ISSUE THREAD

**Issue by GrinlexGH** [Traben-0/entity_sound_features#4]
I have my own server on my computer and when I trying to connect to it, it kicks me with
<details>
<summary>stacktrace</summary>
<br>

```
---- Minecraft Network Protocol Error Report ----
// All lines are down!

Time: 2024-11-20 20:08:14
Description: Playing level event

java.lang.NoSuchMethodError: 'net.minecraft.class_2960 net.minecraft.class_3414.method_14833()'
	at knot//net.minecraft.class_638.handler$zda000$entity_sound_features$esf$discoverEntity(class_638.java:1130)
	at knot//net.minecraft.class_638.method_43207(class_638.java)
	at knot//net.minecraft.class_638.method_8486(class_638.java:493)
	at knot//net.minecraft.class_1937.method_45446(class_1937.java:440)
	at knot//net.minecraft.class_9959.method_62194(class_9959.java:470)
	at knot//net.minecraft.class_638.method_8444(class_638.java:607)
	at knot//net.minecraft.class_1936.method_20290(class_1936.java:85)
	at knot//net.minecraft.class_634.method_11098(class_634.java:1507)
	at knot//net.minecraft.class_2673.method_11535(class_2673.java:46)
	at knot//net.minecraft.class_2673.method_11054(class_2673.java:10)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:27)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:164)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:138)
	at knot//net.minecraft.class_1255.method_5383(class_1255.java:123)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1307)
	at knot//net.minecraft.class_310.method_1514(class_310.java:933)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```
[disconnect-2024-11-20_20.08.14-client.txt](https://github.com/user-attachments/files/17834398/disconnect-2024-11-20_20.08.14-client.txt)
</details>

server properties:
[server.properties.txt](https://github.com/user-attachments/files/17834411/server.properties.txt)

**Comment by GrimPlayzs** [comment]
Related: https://github.com/Traben-0/entity_sound_features/issues/5

**Comment by Traben-0** [comment]
Does it still crash with only etf emf and esf installed?

**Comment by GrimPlayzs** [comment]
Yes

**Comment by GrimPlayzs** [comment]
For me this time with only the three installed I can't even get into the world.

**Comment by Traben-0** [comment]
I can't seem to replicate this at all, can i get your world?

**Comment by GrinlexGH** [comment]
it's happening on every world, even on new
[Новый мир.zip](https://github.com/user-attachments/files/17848868/default.zip)

**Comment by GrimPlayzs** [comment]
I only have EMF, ESF, and ETF on my test instance. I use Hypixel as a good testing ground. Game crashes after a few seconds. I also joined my private server can't even get into the world game crashes instantly. The crash report indicates the same error consistently.

**Comment by Traben-0** [comment]
I did try hypixel as someone mentioned it specifically

I am able to load worlds perfectly fine, 1.21.3 fabric

What packs are loaded?

**Comment by GrimPlayzs** [comment]
I don't have any packs loaded on my test instance.

**Comment by GrinlexGH** [comment]
me too

**Comment by Traben-0** [comment]
> it's happening on every world, even on new [Новый мир.zip](https://github.com/user-attachments/files/17848868/default.zip)

i still dont crash with this world either

**Comment by Traben-0** [comment]
fixed, it was a wrong file upload that apparently my system would not re-download as i had the correct file already on my end

**Comment by Traben-0** [comment]
curseforge might take a few minutes too verify the file but modrinth ahs the correct one
